### PR TITLE
Create k8s cluster

### PR DESCRIPTION
**Pull request by wl2484**
## Assumptions
1. The shared kubernetes (k8s) cluster was created manually via the IBM Cloud console
2. The `apikey.json` to access the shared k8s cluster is stored as `~/.bluemix/apikey_shopcarts.json` at each member's local
3. The `apikey_shopcarts.json` to access the shared k8s cluster would be copied into the container at path `/home/vscode/.ibm/apikey_shopcarts.json` 

## Changes
1. Assign the name of the shared k8s cluster in the Makefile
2. Copy `apikey_shopcarts.json` to container
3. Correct project naming to `Shopcarts Service`
4. Remove redundant intro in the README

### CODE REVIEW

**Comment by LillisLuo** [comment]
Hi Wan-Yu, I noticed that there are someextra lines in **install-tools.sh** under **.devcontainer/scripts** directory in lab-bluemix-cf lab. But I'm not sure whether it is necessary to add those lines.

**Comment by wl2484** [comment]
> Hi Wan-Yu, I noticed that there are someextra lines in **install-tools.sh** under **.devcontainer/scripts** directory in lab-bluemix-cf lab. But I'm not sure whether it is necessary to add those lines.

Hi @LillisLuo, thank you for the reminder! I'm not sure if we will need the YQ tool (e.g. YAML processor), either, let me raise this in the homework channel!

**Comment by wl2484** [comment]
Hi @LillisLuo, I added one [additional commit](f7e887e9b23855bc4edeb306d919f4c37997aa67) for creating k8s cluster namespace, and setting default k8s cluster namespace at local. Let me know if you have other comments, thanks a lot!

**Comment by wl2484** [comment]
> > Hi Wan-Yu, I noticed that there are someextra lines in **install-tools.sh** under **.devcontainer/scripts** directory in lab-bluemix-cf lab. But I'm not sure whether it is necessary to add those lines.
> 
> Hi @LillisLuo, thank you for the reminder! I'm not sure if we will need the YQ tool (e.g. YAML processor), either, let me raise this in the homework channel!

Hi @LillisLuo, according to Professor's [reply](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1689595168591479?thread_ts=1689566356.119099&cid=C05BNCWBJBW) we wouldn't need to install YQ tool!

**Comment by LillisLuo** [comment]
> > > Hi Wan-Yu, I noticed that there are someextra lines in **install-tools.sh** under **.devcontainer/scripts** directory in lab-bluemix-cf lab. But I'm not sure whether it is necessary to add those lines.
> > 
> > 
> > Hi @LillisLuo, thank you for the reminder! I'm not sure if we will need the YQ tool (e.g. YAML processor), either, let me raise this in the homework channel!
> 
> Hi @LillisLuo, according to Professor's [reply](https://nyu-devops-summer23.slack.com/archives/C05BNCWBJBW/p1689595168591479?thread_ts=1689566356.119099&cid=C05BNCWBJBW) we wouldn't need to install YQ tool!

Hi Wan-Yu, thanks for your reply. I have seen the response from professor. Just approved.

**Review by LillisLuo — APPROVED** [review]

**Pull request merged**
