### PR TITLE
Model Enhancement

### PR DESCRIPTION
**Pull request by wl2484**
1. Fix foreign key import
2. Create ModelBase for sharing query methods
3. Resolve existing non-F401 linter warnings

### CODE REVIEW

**Comment by LillisLuo** [comment]
I think we can comment the **db.drop_all()** at line 45 and 85 for now since these line will drop the two tables. We can keep the two lines for now to check how the test cases would influence the database.

**Comment by wl2484** [comment]
> I think we can comment the **db.drop_all()** at line 45 and 85 for now since these line will drop the two tables. We can keep the two lines for now to check how the test cases would influence the database.

good point! how about comment out these two lines for now?

**Comment by LillisLuo** [comment]
> 

I'm good with that

**Comment by LillisLuo** [comment]
> > I think we can comment the **db.drop_all()** at line 45 and 85 for now since these line will drop the two tables. We can keep the two lines for now to check how the test cases would influence the database.
> 
> good point! how about comment out these two lines for now?

I'm good with that

**Review by LillisLuo — APPROVED** [review]

**Pull request merged**
