### PR TITLE
Create BDD base environment

### PR DESCRIPTION
**Pull request by wl2484**
## Goal
Prepare BDD base environment for the team's convenience. Rest stories in the Sprint such as (1) behavior scenarios & steps development, (2) BDD workflow, as well as (3) the Integration Test Stage in the cloud will all depend on this change.

## Changes
1. Add BDD required dependencies
2. Add BDD base features, steps, and environment
4. Set image tag to 1.1

## Verification
BDD

### CODE REVIEW

**Review by LillisLuo — APPROVED** [review]
All good!

**Comment by wl2484** [comment]
@LillisLuo wow!! thank you for the instant review 👍🏻 let me fix the lint error lol

**Comment by LillisLuo** [comment]
> @LillisLuo wow!! thank you for the instant review 👍🏻 let me fix the lint error lol
Yes sure, I have reviewed the modified files and didn't notice the lint error. I'm working on the UI page and this environment is really helpful!

**Comment by LillisLuo** [comment]
Looks good after resolving the lint error!

**Comment by wl2484** [comment]
Finally, the lint errors are resolved, nevertheless, I found it that the `make lint` command does not expose lint errors in the features/ folder at local. We might need another way to discover it 🤔

**Pull request merged**
