### PR TITLE
Create a database in docker

### PR DESCRIPTION
**Pull request by wl2484**
## Goal

1. Name the docker containers
2. Given the scripts for creating the PostgresSQL DB in the docker container is given, add corresponding steps for accessing the DB to README.

### Validation At Local

access-db-via-docker-exec

verification-at-local

### CODE REVIEW

**Comment by wl2484** [comment]
Note that we need to figure out a way to create custom user/pass/database in Postgres.

**Review by LillisLuo — COMMENTED** [review]
Hi Wan-Yu, I have a question about the modification in **Database Connection** model in README, I use another command to get into the database and table.

**Comment by wl2484** [comment]
Hi @LillisLuo, thank you for the comments, would you like to share the command? I can add it accordingly to the README. Or it is fine for you to add a commit to this PR directly :) Thanks a lot!

**Comment by LillisLuo** [comment]
Hi @wl2484 , sure I will share the process in the comment. I used the TDD project because there exists well defined attributes. I used the command "docker exec -it lab-flask-tdd_devcontainer-postgres-1 psql -U postgres" to connect the database in container.
截屏2023-06-26 18 36 56

**Review by momo100110 — APPROVED** [review]

**Review by LillisLuo — APPROVED** [review]
All good for this story! Thank you Wan-Yu!

**Comment by wl2484** [comment]
Hi @LillisLuo, have added a commit according to the review comments, thank you for the great suggestion!

**Pull request merged**
